# Generated by Django 5.1.4 on 2026-06-15 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_userprofile_invitation_code_invited_by_pointtransaction_category_user_efootball_id_nullable",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_avatar",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.CreateModel(
            name="AccountVerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_code", models.CharField(blank=True, max_length=6)),
                ("entered_code", models.CharField(blank=True, max_length=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("code_entered", "Code soumis"),
                            ("verified", "Vérifié"),
                            ("rejected", "Refusé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de vérification",
                "verbose_name_plural": "Demandes de vérification",
                "ordering": ["-created_at"],
            },
        ),
    ]
