# Generated by Django 5.1.4 on 2026-06-09 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/', verbose_name='Image')),
                ('points_cost', models.PositiveIntegerField(verbose_name='Coût en points')),
                ('quantity_available', models.IntegerField(default=-1, help_text='-1 = illimitée', verbose_name='Quantité disponible')),
                ('category', models.CharField(choices=[('ingame', 'In-Game'), ('gift', 'Carte cadeau'), ('premium', 'Premium')], default='ingame', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Récompense',
                'verbose_name_plural': 'Récompenses',
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('delivered', 'Livrée')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Note admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='rewards.reward')),
            ],
            options={
                'verbose_name': 'Demande de récompense',
                'verbose_name_plural': 'Demandes de récompenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('redemption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rewards.redemptionrequest')),
            ],
            options={
                'verbose_name': 'Historique statut demande',
                'ordering': ['-created_at'],
            },
        ),
    ]
