# Generated by Django 5.1.4 on 2026-06-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_overhaul_add_missionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='link',
            field=models.URLField(blank=True, help_text='URL pour les missions externes (ex: page Instagram)', null=True, verbose_name='Lien externe'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='max_monthly_completions',
            field=models.PositiveIntegerField(default=0, help_text='0 = une seule fois (permanente)', verbose_name='Max complétions/mois'),
        ),
    ]
