# Generated by Django 5.1.4 on 2026-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0003_alter_mission_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionrequest",
            name="instagram_username",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom d'utilisateur Instagram"
            ),
        ),
    ]
