# Generated by Django 5.1.4 on 2026-06-09 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('register', 'Inscription'), ('email_verified', 'Email vérifié'), ('reward_request', 'Demande récompense'), ('reward_accepted', 'Récompense acceptée'), ('reward_rejected', 'Récompense refusée'), ('mission_complete', 'Mission complétée'), ('daily_reward', 'Récompense quotidienne'), ('admin', 'Action admin'), ('password_reset', 'Réinitialisation mot de passe')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-created_at'],
            },
        ),
    ]
